### ISSUE TITLE
Rename extension, update assets & documentation

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/camunda-cloud-github-action#23]
Hi Josh,

I hope today finds you well! This issue is being opened to ask if you would be open to renaming your extension on GitHub to reference Camunda Platform 8 rather than Camunda Cloud after its release on April 12th, 2022. (For example: camunda-platform-8-github-action) This change will also likely impact any screenshots you have in the README that reference Camunda Cloud or previous versions of Camunda Platform, and this will likely need to also be updated throughout the repo's documentation as a whole. You can also make use of [Shields.io badges](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to indicate which version of Camunda your extension is compatible with.

While it is not a requirement that you rename your extension to align with Camunda Platform 8, we would greatly appreciate it if you could make these changes, and merge them anytime after April 12th, 2022.

if you have any questions or require any assistance, please do not hesitate to reach out to Amara! :)

**Comment by akeller** [comment]
@jwulf is this something you are taking care of?

**Comment by akeller** [comment]
I added the badge to the README. @jwulf can you take care of the rest of the renaming work? Otherwise, I'll circle back around and get to it at some point in the distant.
